version: 2

sources:
  - name: dbt_sprawira
    database: development 
    schema: dbt_sprawira
    freshness:
          error_after: {count: 10, period: hour}
    loaded_at_field: updated_at
    tables:
      - name: dev_source
        